name: sari_scan
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+5

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobile_scanner: ^7.1.3
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.14.1
  intl: ^0.20.2
  barcode_widget: ^2.0.4
  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.4.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon.png
    - assets/icon-transparent.png
